name: Deploy

on:
  pull_request:
    types:
    - closed
    branches:
    - dev
    - staging
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ${{ github.event.pull_request.base.ref || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set NAME variable
        id: set_name
        run: |
          if [ "${{ github.event.pull_request.base.ref || github.ref_name }}" = "dev" ]; then
            echo "NAME=develop" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref || github.ref_name }}" = "staging" ]; then
            echo "NAME=pre" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref || github.ref_name }}" = "main" ]; then
            echo "NAME=prod" >> $GITHUB_ENV
          else
            echo "NAME=" >> $GITHUB_ENV
          fi
      - name: Echo NAME
        run: echo "NAME is $NAME"
