name: Deploy_wf

on:
  pull_request:
    branches: [ "main" ]
    types: [synchronize]
    paths:
      - .github/workflows/**
  pull_request_review:
    types: [submitted]   

jobs:
  paso1:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Build (dummy step)
        run: echo "paso1"
  paso2:
    runs-on: ubuntu-latest
    needs: paso1
    steps:
      - name: Build (dummy step)
        run: echo "paso2"
