name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - staging
      - main
jobs:
  deploy:
    name: Deploy ${{github.event.pull_request.base.ref}}
    runs-on: ubuntu-latest
    env:
      NAME: ${{ github.event.pull_request.base.ref == 'develop' && 'develop' || github.event.pull_request.base.ref == 'staging' && 'pre' || github.event.pull_request.base.ref == 'main' && 'prod' || '' }}
    steps:
      - name: Echo NAME
        run: echo "NAME is $NAME"

