name: Demo Approvals

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: '¿Confirmas el deploy? Escribe "yes" para continuar'
        required: true
        default: 'no'

jobs:
  hello-normal:
    runs-on: ubuntu-latest
    steps:
      - name: Hello normal
        run: echo "Hello"

  hello-with-confirm:
    runs-on: ubuntu-latest
    needs: hello-normal
    if: ${{ github.event.inputs.confirm == 'yes' }}
    steps:
      - name: Hello world con confirmación manual
        run: echo "Hello World"

  hello-with-environment:
    runs-on: ubuntu-latest
    needs: hello-with-confirm
    environment: prod
    steps:
      - name: Hello world again con environment prod
        run: echo "Hello World Again"
